---
- hosts: all
  become: yes
  tasks:
  - name: Ensure NTP (for time synchronization) is installed.
    yum: name=ntp state=present
  - name: Ensure NTPO is running.
    service: name=ntpd state=started enabled=yes
